<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="8" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-24T22:26:46 IST" name="WebClientSaasAppSuite" finished-at="2022-04-24T22:27:08 IST" duration-ms="22006">
    <groups>
    </groups>
    <test started-at="2022-04-24T22:26:46 IST" name="WebClientSaasAppTest" finished-at="2022-04-24T22:27:08 IST" duration-ms="22006">
      <class name="com.saas.app.testCases.TC_LoginPage">
        <test-method is-config="true" signature="initEnvironment()[pri:0, instance:com.saas.app.testCases.TC_LoginPage@42e3ede4]" started-at="2022-04-24T22:26:08 IST" name="initEnvironment" finished-at="2022-04-24T22:26:46 IST" duration-ms="38103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initEnvironment -->
        <test-method signature="valLoginPageTest()[pri:0, instance:com.saas.app.testCases.TC_LoginPage@42e3ede4]" started-at="2022-04-24T22:26:46 IST" name="valLoginPageTest" finished-at="2022-04-24T22:26:54 IST" duration-ms="8344" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valLoginPageTest -->
        <test-method is-config="true" signature="shutDownEnvironment()[pri:0, instance:com.saas.app.testCases.TC_LoginPage@42e3ede4]" started-at="2022-04-24T22:27:08 IST" name="shutDownEnvironment" finished-at="2022-04-24T22:27:14 IST" duration-ms="6060" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDownEnvironment -->
      </class> <!-- com.saas.app.testCases.TC_LoginPage -->
      <class name="com.saas.app.testCases.TC_LogoutPage">
        <test-method signature="logoutPageTest()[pri:0, instance:com.saas.app.testCases.TC_LogoutPage@15cafec7]" started-at="2022-04-24T22:27:07 IST" name="logoutPageTest" finished-at="2022-04-24T22:27:08 IST" duration-ms="1011" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.saas.app.testCases.TC_LogoutPage.logoutPageTest(TC_LogoutPage.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutPageTest -->
      </class> <!-- com.saas.app.testCases.TC_LogoutPage -->
      <class name="com.saas.app.testCases.TC_ContactsPage">
        <test-method signature="valCreateNewContact(java.lang.String,java.lang.String)[pri:0, instance:com.saas.app.testCases.TC_ContactsPage@2a3c96e3]" started-at="2022-04-24T22:26:57 IST" name="valCreateNewContact" data-provider="newContact" finished-at="2022-04-24T22:27:02 IST" duration-ms="5829" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Name1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Testcust1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valCreateNewContact -->
        <test-method signature="valCreateNewContact(java.lang.String,java.lang.String)[pri:0, instance:com.saas.app.testCases.TC_ContactsPage@2a3c96e3]" started-at="2022-04-24T22:27:02 IST" name="valCreateNewContact" data-provider="newContact" finished-at="2022-04-24T22:27:07 IST" duration-ms="4461" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Name2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Testcust2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valCreateNewContact -->
      </class> <!-- com.saas.app.testCases.TC_ContactsPage -->
    </test> <!-- WebClientSaasAppTest -->
  </suite> <!-- WebClientSaasAppSuite -->
</testng-results>
